### ISSUE TITLE
Warning from awk when running ztap -c

### ISSUE THREAD

**Issue by smmckay** [mattmc3/tapz#1]
When I run `ztap -c` I get a warning from awk:

```
awk: /REDACTED/.ztap/bin/colorize_tap:23: warning: regexp escape sequence `\#' is not a known regexp operator
```

System info:
```
% awk -V
GNU Awk 5.1.1, API: 3.1 (GNU MPFR 4.1.0-p13, GNU MP 6.2.1)
Copyright (C) 1989, 1991-2021 Free Software Foundation.
```
```
% uname -a
Linux framework 5.16.5-arch1-1 #1 SMP PREEMPT Tue, 01 Feb 2022 21:42:50 +0000 x86_64 GNU/Linux
```
If I remove the backslash before # in colorize_tap then the warning goes away and colorization still works.

**Comment by mattmc3** [comment]
@smmckay - Thanks for this! Great catch. You're right, the final fail status was getting reset on each test run with the check I was using. I just pushed a commit to resolve this. Feel free to re-open this issue if you still see the issue.
